name: ENV variables
on: push
env:
  WF_ENV: ${{ secrets.WF_ENV }}


jobs:
  log-env:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Log env variables
        env:
          STEP_ENV: Only available in step log env variables
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
          
      - name: step number 2
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"

  log-default-env:
    runs-on: ubuntu-latest
    steps:
      - name: step of job2
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
